name: Propose a new requirement or use case
description: Suggest something the specification should support
title: "[Requirement]: "
labels: ["user-need"]
body:

  - type: textarea
    id: need
    attributes:
      label: What is the need, use case, or requirement?
      description: Describe the problem or capability that is missing or unclear.
      placeholder: >
        Example: Planning officers need to know when a condition replaces an earlier one so they can enforce the correct version.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: input
    id: theme
    attributes:
      label: Theme / tags
      description: Add one or more tags, separated by commas.
      placeholder: e.g. compliance, performance, automation, transparency

  - type: checkboxes
    id: area
    attributes:
      label: Which part of the specification might this affect?
      options:
        - label: Submission (planning application)
        - label: Decision stage
        - label: Both
        - label: Not sure
