name: Daily issue tracking update

on:
  schedule:
    # Run daily at 9:00 AM UTC (adjust as needed)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-issue-tracking:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make init
        
    - name: Set up environment variables
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "GITHUB_TOKEN=$GITHUB_TOKEN" > .env
        
    - name: Generate issue data
      run: |
        make issue-tracking-data
        
    - name: Generate issue tracking index
      run: |
        make issue-tracking-report
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        make commit-issue-tracking
